### ISSUE TITLE
Proofread artifact in integrate-in-existing-app.md

### ISSUE THREAD

**Issue by okarmazin** [JetBrains/kotlin-mobile-docs#25]
> KMM presumes that the best user experience is when it is _native to theheavily dependent on the_ platform itself, and therefore we _don’t recommend sharing it in KMMshould not be shared_.

**Comment by KaterinaPetrova** [comment]
Thanks for reporting! Fixed in https://github.com/JetBrains/kotlin-mobile-docs/commit/dede0faeeff920a31af020e0ed1e92a8ba74f296
